#!/usr/bin/env bash
# Documentation linter: enforces docs/process/documentation-standard.md.
#
# Usage:
#   scripts/check-docs.sh            # check every tracked Markdown file
#   scripts/check-docs.sh a.md b.md  # check specific files
set -uo pipefail

FAILED=0
CHECKED=0

# .github/ holds issue and pull request templates, which GitHub renders with its
# own rules; CHANGELOG.md is generated by release-please.
is_excluded() {
  case "$1" in
    .github/*|CHANGELOG.md|node_modules/*|*/node_modules/*) return 0 ;;
    *.pt-BR.md|*.es.md) return 0 ;;  # translated copies are exempt from R1
    *) return 1 ;;
  esac
}

fail() {
  printf '  \033[31mFAIL\033[0m %s: %s\n' "$1" "$2"
  FAILED=1
}

has_marker() { grep -qF "<!-- lint: $2 -->" "$1"; }

# Strips fenced code blocks so code samples do not trip the prose checks.
prose_only() {
  awk '/^[[:space:]]*```/ { inblock = !inblock; next } !inblock' "$1"
}

check_file() {
  local file="$1"
  CHECKED=$((CHECKED + 1))
  local in_docs=0
  [[ "$file" == docs/* ]] && in_docs=1
  # Pages written for a visitor keep R1 and R2 and skip the rest: 5W2H is the
  # shape of a decision record, and a reader learning to read a BGP table is
  # not reading one (R3 note in the standard).
  [[ "$file" == docs/wiki/* ]] && in_docs=0

  # R2 — TL;DR
  if ! has_marker "$file" "no-tldr" && ! grep -qE '^#{2,3} TL;DR' "$file"; then
    fail "$file" "missing '## TL;DR' section (R2)"
  fi

  # R1 — English prose. Accented Latin characters are a reliable signal of
  # Portuguese or Spanish text in a document that should be English.
  if ! has_marker "$file" "allow-non-english"; then
    local hits
    # Only lowercase-initial words count: proper names such as "André" are fine.
    hits=$(prose_only "$file" \
      | grep -nE '(^|[^[:alpha:]])[a-z][[:alpha:]]*[ãõçñáéíóúâêîôûàèìòùü]' \
      | head -3 || true)
    if [[ -n "$hits" ]]; then
      fail "$file" "non-English prose detected (R1): $(echo "$hits" | tr '\n' ' ' | cut -c1-120)"
    fi
  fi

  [[ $in_docs -eq 1 ]] || return

  # R3 — 5W2H
  if ! grep -qE '^#{2,3} 5W2H' "$file"; then
    fail "$file" "missing '## 5W2H' section (R3)"
  else
    local q
    for q in "What" "Why" "Who" "Where" "When" "How" "How much"; do
      grep -qE "\*\*${q}\*\*" "$file" || fail "$file" "5W2H is missing the '${q}' entry (R3)"
    done
  fi

  # R4 — RFC 2119 keywords
  if ! grep -qE '\b(MUST NOT|MUST|SHALL NOT|SHALL|SHOULD NOT|SHOULD|REQUIRED|RECOMMENDED|MAY|OPTIONAL)\b' "$file"; then
    fail "$file" "no RFC 2119 keyword found (R4)"
  fi

  # R5 — at least one Mermaid diagram
  if ! has_marker "$file" "no-diagram" && ! grep -qE '^[[:space:]]*```mermaid' "$file"; then
    fail "$file" "no Mermaid diagram (R5); add one or justify with '<!-- lint: no-diagram -->'"
  fi
}

main() {
  local files=()
  if [[ $# -gt 0 ]]; then
    files=("$@")
  else
    mapfile -t files < <(git ls-files '*.md')
  fi

  echo "Checking documentation against docs/process/documentation-standard.md"
  local f
  for f in "${files[@]}"; do
    [[ -f "$f" ]] || continue
    is_excluded "$f" && continue
    check_file "$f"
  done

  if [[ $FAILED -eq 0 ]]; then
    printf '\033[32mOK\033[0m %d file(s) checked, no violations.\n' "$CHECKED"
  else
    printf '\n%d file(s) checked. See docs/process/documentation-standard.md for the rules.\n' "$CHECKED"
  fi
  return $FAILED
}

main "$@"
