#!/usr/bin/env bash
# Publishes docs/wiki/ to the GitHub wiki.
#
# The repository is the source; the wiki is a generated mirror. Editing a page
# in the wiki interface is therefore a mistake waiting to be overwritten — the
# next run of this script replaces it. That is deliberate: a page in the wiki
# escapes the documentation linter and the review rules, and two sources of the
# same page become wrong in one of them.
#
# Usage:
#   scripts/publish-wiki.sh [--dry-run] [--repo owner/name]
#
# Requires the wiki to be enabled. GitHub only allows wikis in a private
# repository on a paid plan, so on a free plan this works once the repository
# is public.
set -euo pipefail

DRY_RUN=0
REPO="${WIKI_REPO:-andrediashexa/nogglass}"
SOURCE="docs/wiki"
IMAGES="docs/design/screens"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --repo) REPO="$2"; shift ;;
    -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

[[ -d "$SOURCE" ]] || { echo "run this from the repository root: $SOURCE not found" >&2; exit 1; }

# Wiki page names come from the file name, so the index has to be Home and the
# rest read as titles rather than as slugs.
page_name() {
  local file="$1" base
  base="$(basename "$file" .md)"
  if [[ "$base" == "README" ]]; then
    echo "Home"
    return
  fi
  # "3-reading-a-bgp-result" becomes "3-Reading-a-bgp-result": the wiki shows
  # the name with dashes as spaces.
  python3 - "$base" <<'PY'
import sys
base = sys.argv[1]
number, _, rest = base.partition("-")
words = rest.split("-")
if words:
    words[0] = words[0].capitalize()
print(f"{number}-" + "-".join(words))
PY
}

staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT

echo "Building the wiki tree in $staging"
mkdir -p "$staging/images"
cp "$IMAGES"/*.png "$staging/images/" 2>/dev/null || echo "  no screenshots found in $IMAGES"

declare -A names
for file in "$SOURCE"/*.md; do
  names["$(basename "$file")"]="$(page_name "$file")"
done

for file in "$SOURCE"/*.md; do
  target="$staging/$(page_name "$file").md"
  python3 - "$file" "$target" <<'PY'
import pathlib
import re
import sys

source, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
text = source.read_text(encoding="utf-8")


def wiki_name(link: str) -> str:
    """Turns a file link into a wiki page name."""
    stem = pathlib.Path(link).stem
    if stem == "README":
        return "Home"
    number, _, rest = stem.partition("-")
    words = rest.split("-")
    if words:
        words[0] = words[0].capitalize()
    return f"{number}-" + "-".join(words)


# Screenshots live beside the pages in the wiki repository, because a private
# repository's raw URLs need a token and would render as broken images.
text = re.sub(r"\]\(\.\./design/screens/([^)]+)\)", r"](images/\1)", text)

# Links between wiki pages become page names.
text = re.sub(r"\]\((\d+-[a-z0-9-]+)\.md\)", lambda m: f"]({wiki_name(m.group(1))})", text)
text = re.sub(r"\]\(README\.md\)", "](Home)", text)

# Links out of the wiki point back at the repository, where those documents
# live and are reviewed.
repo = "https://github.com/andrediashexa/nogglass/blob/main"
text = re.sub(r"\]\(\.\./([^)]+)\)", rf"]({repo}/docs/\1)", text)

target.write_text(text, encoding="utf-8")
PY
  echo "  $(basename "$file") -> $(basename "$target")"
done

if [[ $DRY_RUN -eq 1 ]]; then
  echo
  echo "Dry run. The tree that would be published:"
  ls -1 "$staging"
  exit 0
fi

if ! gh api "repos/$REPO" --jq '.has_wiki' | grep -q true; then
  cat >&2 <<EOF

The wiki is not enabled on $REPO.

GitHub allows wikis in a private repository only on a paid plan; the API accepts
the setting and silently leaves it off. Either make the repository public, or
enable the wiki in Settings once the account can, then run this again.

The pages are already published as files: docs/wiki/ renders on GitHub.
EOF
  exit 1
fi

clone="$(mktemp -d)"
trap 'rm -rf "$staging" "$clone"' EXIT

echo "Cloning the wiki"
git clone -q "https://github.com/$REPO.wiki.git" "$clone"

# Replace rather than merge: the repository is the source, so anything in the
# wiki that is not generated from it is stale by definition.
find "$clone" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -r "$staging/." "$clone/"

cd "$clone"
git add -A
if git diff --cached --quiet; then
  echo "The wiki is already up to date."
  exit 0
fi

git commit -q -m "docs: publish docs/wiki from the repository

Generated by scripts/publish-wiki.sh. Edit the pages in docs/wiki/ and run it
again; edits made here are replaced."
git push -q
echo "Published to https://github.com/$REPO/wiki"
