frr defaults traditional
router bgp 65100
 bgp router-id 172.31.0.2
 no bgp ebgp-requires-policy
 neighbor 172.31.0.3 remote-as 65001
 address-family ipv4 unicast
  network 198.51.100.0/24
  network 203.0.113.0/24
  neighbor 172.31.0.3 activate
 exit-address-family
!
ip route 198.51.100.0/24 blackhole
ip route 203.0.113.0/24 blackhole
